// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	ses "github.com/aws/aws-sdk-go/service/ses"
	mock "github.com/stretchr/testify/mock"
)

// SESClient is an autogenerated mock type for the SESClient type
type SESClient struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: input
func (_m *SESClient) SendEmail(input *ses.SendEmailInput) (*ses.SendEmailOutput, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for SendEmail")
	}

	var r0 *ses.SendEmailOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(*ses.SendEmailInput) (*ses.SendEmailOutput, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(*ses.SendEmailInput) *ses.SendEmailOutput); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ses.SendEmailOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(*ses.SendEmailInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSESClient creates a new instance of SESClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSESClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *SESClient {
	mock := &SESClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
